/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package pl.marcinchwedczuk.expr;

public class App {
    public static void main(String[] args) {
        System.out.println("oki");
    }
}
