/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package pl.marcinchwedczuk.expr;

import pl.marcinchwedczuk.expr.transformers.cglib.CGLibDemo;

public class App {
    public static void main(String[] args) throws Exception {
        CGLibDemo.main(args);
    }
}
